### ISSUE TITLE
[1.16.5] Error when stopping server

### ISSUE THREAD

**Issue by MarioSMB** [henkelmax/gravestone#49]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
When stopping a server, a configuration error is shown which may cause the server to hang forever without actually stopping

**Steps to reproduce the issue**

**Expected behavior**
For the server to stop cleanly and not hang with errors

**Log files**
```
[31Mar2021 15:50:11.462] [Server thread/ERROR] [net.minecraftforge.fml.config.ConfigFileTypeHandler/]: Failed to remove config ./world/serverconfig/gravestone-server.toml from tracker!
java.lang.NullPointerException: null
	at com.electronwill.nightconfig.core.file.FileWatcher.removeWatch(FileWatcher.java:134) ~[core-3.6.2.jar:?]
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.unload(ConfigFileTypeHandler.java:76) ~[forge:?]
	at net.minecraftforge.fml.config.ConfigTracker.closeConfig(ConfigTracker.java:114) ~[forge:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$unloadConfigs$2(ConfigTracker.java:88) ~[forge:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2067) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.unloadConfigs(ConfigTracker.java:88) ~[forge:?]
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:135) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:682) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Versions**
- Minecraft version 1.16.5
- Forge version 36.0.7
- Mod version 1.9.0

**Other mods**
Likely occurs with just Gravestones installed, as this is appears to be a standard Forge error

**Screenshots (Optional)**

**Comment by henkelmax** [comment]
Do you have an editor with the config file open or have you deleted the file while the server was running?

**Comment by MarioSMB** [comment]
I have done neither of those things, I generally attach to the Screen session directly on the server and execute the stop command.

**Comment by MarioSMB** [comment]
Thank you for your feedback, it helped me track down the root of the cause: it appears to have been the Performant mod; their latest update must've changed the config file a lot, and it freaks out when trying to write to the old one on server shutdown.  
I'll file an issue on their tracker so that people can track down the source of the server hanging easily.

**Comment by henkelmax** [comment]
Oh, OK, thanks for letting me know!
