### ISSUE TITLE
Items not saved by gravestone

### ISSUE THREAD

**Issue by U-R-E** [henkelmax/gravestone#65]
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
Items are not saved into the gravestone and fall on the ground instead upon player death

**Steps to reproduce the issue**
Install the mod
add items to inventory
/kill command or die from a mob
head back to the death spot and the items are on the ground splattered around the gravestone

**Expected behavior**
The items to be saved in the gravestone and retrievable upon breaking the gravestone  

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version - 1.16.5
- Forge version - 36.1.4
- Mod version - 1.0.1

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by Thewraith01** [comment]
i have had a similar issue, died in the block space of a fencepost, no grave spawned however no items dropped either

**Comment by henkelmax** [comment]
Does this happen without any other mods?
Are you using plugins?
Please provide your logs.

**Comment by U-R-E** [comment]
There are other mods but the only thing that is different is that we started a new world with the same mods 
No plugins added 

- This is right before the point where I did the /kill command 
[13Jun2021 11:41:56.288] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.NoSuchMethodException: net.minecraft.entity.player.PlayerEntity.dropInventory()
[13Jun2021 11:41:56.289] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at java.lang.Class.getDeclaredMethod(Class.java:2130)
[13Jun2021 11:41:56.289] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findMethod(ObfuscationReflectionHelper.java:160)
[13Jun2021 11:41:56.289] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	... 34 more

- Below is the log of the point where I did the /kill command to test it out. I had wood planks in my inventory and hotbar 
[13Jun2021 11:41:56.292] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Nuclear_XD_2 fell out of the world
[13Jun2021 11:41:56.298] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Nuclear_XD_2: Killed Nuclear_XD_2]
[13Jun2021 11:41:59.225] [Server thread/INFO] [STDOUT/]: [tschipp.fakename.CommandFakeName:lambda$register$1:56]: true
[13Jun2021 11:41:59.225] [Server thread/INFO] [STDOUT/]: [tschipp.fakename.CommandFakeName:lambda$register$1:56]: 2
[13Jun2021 11:41:59.235] [Netty Epoll Server IO #2/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize tschipp.fakename.CommandFakeName$FakenameArgumentType@6789715b (class tschipp.fakename.CommandFakeName$FakenameArgumentType) - will not be sent to client!
[13Jun2021 11:43:21.182] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Server] I see what happened, the items fell on the ground

**Comment by henkelmax** [comment]
Please send the full logs via GitHub gist

**Comment by henkelmax** [comment]
Closed due to inactivity
