### ISSUE TITLE
Error when right clicking grave on dedicated server

### ISSUE THREAD

**Issue by Bricktricker** [henkelmax/gravestone#7]
**Bug description**
The dedicated server generates a NullPointerException when right clicking on a grave.

**Steps to reproduce the issue**
1. Join a dedicated server with this mod
2. Die to generate a grave
3. right click on the grave

**Expected behavior**
Get a chat message when the player has died.

**Error**
```
[26Sep2020 14:29:27.152] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at de.maxhenkel.gravestone.util.Tools.timeToString(Tools.java:39) ~[?:?]
	at de.maxhenkel.gravestone.tileentity.GraveStoneTileEntity.getTimeString(GraveStoneTileEntity.java:139) ~[?:?]
	at de.maxhenkel.gravestone.blocks.GraveStoneBlock.onBlockActivated(GraveStoneBlock.java:148) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onBlockActivated(AbstractBlock.java:726) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:347) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.processTryUseItemOnBlock(ServerPlayNetHandler.java:917) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.processPacket(CPlayerTryUseItemOnBlockPacket.java:45) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.processPacket(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:19) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(TickDelayedTask.java:20) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:139) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.run(RecursiveEventLoop.java:22) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:754) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:156) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:109) ~[?:?]
	at net.minecraft.server.MinecraftServer.driveOneInternal(MinecraftServer.java:737) ~[?:?]
	at net.minecraft.server.MinecraftServer.driveOne(MinecraftServer.java:731) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveUntil(ThreadTaskExecutor.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.runScheduledTasks(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:663) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```
It look like the server tries to access the `dateFormat` field in the `ClientConfig` class, but its null on the dedicated server.

**Versions**
- Minecraft version: 1.16.3
- Forge version: 34.0.1
- Mod version: 1.16.3-1.0.0 (commit `1ca44c9c30d172a3996fd1b7dc6e8a23fdd7e0de`)

**Other mods**
None

**Comment by henkelmax** [comment]
Thank you for reporting this issue!
